replicaCount: 2

image:
  repository: url-shortener
  tag: dev
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: true
  host: short.local

probes:
  readiness:
    path: /health
    initialDelaySeconds: 3
  liveness:
    path: /health
    initialDelaySeconds: 10